##################
# Static Files
##################

group:

  # cljstyle configuration
  - repos: |
      Wall-Brew-Co/brew-bot
      Wall-Brew-Co/brewtility
      Wall-Brew-Co/clj-xml
      Wall-Brew-Co/common-beer-data
      Wall-Brew-Co/common-beer-format
      Wall-Brew-Co/keg
      Wall-Brew-Co/lein-sealog
      Wall-Brew-Co/spoon
    files:
      - source: sources/clojure/.cljstyle
        dest: .cljstyle

  # clj-kondo configuration
  - repos: |
      Wall-Brew-Co/brew-bot
      Wall-Brew-Co/brewtility
      Wall-Brew-Co/clj-xml
      Wall-Brew-Co/common-beer-data
      Wall-Brew-Co/common-beer-format
      Wall-Brew-Co/keg
      Wall-Brew-Co/lein-sealog
      Wall-Brew-Co/spoon
    files:
      - source: sources/clojure/cljkondo/config.edn
        dest: .clj-kondo/config.edn

  # .gitignore configuration
  - repos: |
      Wall-Brew-Co/brew-bot
      Wall-Brew-Co/brewtility
      Wall-Brew-Co/clj-xml
      Wall-Brew-Co/common-beer-data
      Wall-Brew-Co/common-beer-format
      Wall-Brew-Co/keg
      Wall-Brew-Co/lein-sealog
      Wall-Brew-Co/spoon
    files:
      - source: sources/clojure/.gitignore
        dest: .gitignore

  # Sealog configuration
  - repos: |
      Wall-Brew-Co/brew-bot
      Wall-Brew-Co/brewtility
      Wall-Brew-Co/clj-xml
      Wall-Brew-Co/common-beer-data
      Wall-Brew-Co/common-beer-format
      Wall-Brew-Co/keg
      Wall-Brew-Co/lein-sealog
      Wall-Brew-Co/spoon
    files:
      - source: sources/clojure/sealog/config.edn
        dest: .sealog/config.edn

  # Code of Conduct
  - repos: |
      Wall-Brew-Co/brew-bot
      Wall-Brew-Co/brewtility
      Wall-Brew-Co/clj-xml
      Wall-Brew-Co/common-beer-data
      Wall-Brew-Co/common-beer-format
      Wall-Brew-Co/keg
      Wall-Brew-Co/lein-sealog
      Wall-Brew-Co/spoon
    files:
      - source: sources/community/CODE_OF_CONDUCT.md
        dest: CODE_OF_CONDUCT.md

  # CODEOWNERS
  - repos: |
      Wall-Brew-Co/brew-bot
      Wall-Brew-Co/brewtility
      Wall-Brew-Co/clj-xml
      Wall-Brew-Co/common-beer-data
      Wall-Brew-Co/common-beer-format
      Wall-Brew-Co/keg
      Wall-Brew-Co/lein-sealog
      Wall-Brew-Co/spoon
    files:
      - source: sources/community/CODEOWNERS
        dest: CODEOWNERS

  # Security Policy
  - repos: |
      Wall-Brew-Co/brew-bot
      Wall-Brew-Co/brewtility
      Wall-Brew-Co/clj-xml
      Wall-Brew-Co/common-beer-data
      Wall-Brew-Co/common-beer-format
      Wall-Brew-Co/keg
      Wall-Brew-Co/lein-sealog
      Wall-Brew-Co/spoon
    files:
      - source: sources/community/SECURITY.md
        dest: SECURITY.md

  # Issue and Pull Request Templates
  - repos: |
      Wall-Brew-Co/brew-bot
      Wall-Brew-Co/brewtility
      Wall-Brew-Co/clj-xml
      Wall-Brew-Co/common-beer-data
      Wall-Brew-Co/common-beer-format
      Wall-Brew-Co/keg
      Wall-Brew-Co/lein-sealog
      Wall-Brew-Co/spoon
    files:
      - source: sources/github-actions/ISSUE_TEMPLATE/bug_report.md
        dest: .github/ISSUE_TEMPLATE/bug_report.md
      - source: sources/github-actions/ISSUE_TEMPLATE/feature_request.md
        dest: .github/ISSUE_TEMPLATE/feature_request.md
      - source: sources/github-actions/PULL_REQUEST_TEMPLATE.md
        dest: .github/PULL_REQUEST_TEMPLATE.md

  # Developer Documentation
  - repos: |
      Wall-Brew-Co/brew-bot
      Wall-Brew-Co/brewtility
      Wall-Brew-Co/clj-xml
      Wall-Brew-Co/common-beer-data
      Wall-Brew-Co/common-beer-format
      Wall-Brew-Co/keg
      Wall-Brew-Co/lein-sealog
      Wall-Brew-Co/spoon
    files:
      - source: sources/community/documentation/developing/001_required_tooling.md
        dest: doc/developing/001_required_tooling.md
      - source: sources/community/documentation/developing/002_managed_tooling.md
        dest: doc/developing/002_managed_tooling.md
      - source: sources/community/documentation/developing/003_contribution_guidelines.md
        dest: doc/developing/003_contribution_guidelines.md

  # Clojure Patterns
  - repos: |
      Wall-Brew-Co/brew-bot
      Wall-Brew-Co/brewtility
      Wall-Brew-Co/clj-xml
      Wall-Brew-Co/common-beer-data
      Wall-Brew-Co/common-beer-format
      Wall-Brew-Co/keg
      Wall-Brew-Co/lein-sealog
      Wall-Brew-Co/spoon
    files:
      - source: sources/community/documentation/clojure/patterns/symbolic_keywords.md
        dest: doc/clojure/patterns/symbolic_keywords.md

  # Generic CI/CD
  - repos: |
      Wall-Brew-Co/brew-bot
      Wall-Brew-Co/brewtility
      Wall-Brew-Co/clj-xml
      Wall-Brew-Co/common-beer-data
      Wall-Brew-Co/common-beer-format
      Wall-Brew-Co/keg
      Wall-Brew-Co/lein-sealog
      Wall-Brew-Co/spoon
    files:
      - source: sources/github-actions/labels.yml
        dest: .github/labels.yml
      - source: sources/github-actions/workflows/label.yml
        dest: .github/workflows/label.yml
      - source: sources/github-actions/workflows/sync_labels.yml
        dest: .github/workflows/sync_labels.yml
      - source: sources/github-actions/workflows/todo.yml
        dest: .github/workflows/todo.yml
      - source: sources/github-actions/workflows/contributors.yml
        dest: .github/workflows/contributors.yml
      - source: sources/github-actions/workflows/greetings.yml
        dest: .github/workflows/greetings.yml
      - source: sources/github-actions/labeler.yml
        dest: .github/labeler.yml

  # Renovate Configuration
  - repos: |
      Wall-Brew-Co/brew-bot
      Wall-Brew-Co/brewtility
      Wall-Brew-Co/clj-xml
      Wall-Brew-Co/common-beer-data
      Wall-Brew-Co/common-beer-format
      Wall-Brew-Co/keg
      Wall-Brew-Co/lein-sealog
      Wall-Brew-Co/spoon
    files:
      - source: sources/github-actions/renovate.json
        dest: renovate.json

  # Clojure CI/CD
  - repos: |
      Wall-Brew-Co/brew-bot
      Wall-Brew-Co/brewtility
      Wall-Brew-Co/clj-xml
      Wall-Brew-Co/common-beer-data
      Wall-Brew-Co/common-beer-format
      Wall-Brew-Co/keg
      Wall-Brew-Co/lein-sealog
      Wall-Brew-Co/spoon
    files:
      - source: sources/github-actions/workflows/clojure.yml
        dest: .github/workflows/clojure.yml
      - source: sources/github-actions/workflows/deploy_to_clojars.yml
        dest: .github/workflows/deploy_to_clojars.yml
      - source: sources/github-actions/workflows/format.yml
        dest: .github/workflows/format.yml
      - source: sources/github-actions/workflows/lint.yml
        dest: .github/workflows/lint.yml
      - source: sources/github-actions/workflows/scanner.yml
        dest: .github/workflows/scanner.yml

  # cljdoc CI/CD
  ## This exists since Leiningen plugin projects do not have a separate CLJdoc workflow
  - repos: |
      Wall-Brew-Co/brew-bot
      Wall-Brew-Co/brewtility
      Wall-Brew-Co/clj-xml
      Wall-Brew-Co/common-beer-data
      Wall-Brew-Co/common-beer-format
      Wall-Brew-Co/keg
      Wall-Brew-Co/spoon
    files:
      - source: sources/github-actions/workflows/cljdoc_test.yml
        dest: .github/workflows/cljdoc_test.yml

  # Clojurescript CI/CD
  - repos: |
      Wall-Brew-Co/brew-bot
      Wall-Brew-Co/brewtility
      Wall-Brew-Co/common-beer-data
      Wall-Brew-Co/common-beer-format
      Wall-Brew-Co/spoon
    files:
      - source: sources/github-actions/workflows/clojurescript.yml
        dest: .github/workflows/clojurescript.yml

##################
# Templated Files
##################

Wall-Brew-Co/brew-bot:
  - source: sources/templates/LICENSE
    dest: LICENSE
    template:
      year:
        created: 2020
        current: 2024
  - source: sources/templates/CONTRIBUTING.md
    dest: CONTRIBUTING.md
    template:
      repo:
        name: brew-bot


Wall-Brew-Co/brewtility:
  - source: sources/templates/LICENSE
    dest: LICENSE
    template:
      year:
        created: 2020
        current: 2024
  - source: sources/templates/CONTRIBUTING.md
    dest: CONTRIBUTING.md
    template:
      repo:
        name: brewtility

Wall-Brew-Co/clj-xml:
  - source: sources/templates/LICENSE
    dest: LICENSE
    template:
      year:
        created: 2020
        current: 2024
  - source: sources/templates/CONTRIBUTING.md
    dest: CONTRIBUTING.md
    template:
      repo:
        name: clj-xml

Wall-Brew-Co/common-beer-data:
  - source: sources/templates/LICENSE
    dest: LICENSE
    template:
      year:
        created: 2022
        current: 2024
  - source: sources/templates/CONTRIBUTING.md
    dest: CONTRIBUTING.md
    template:
      repo:
        name: common-beer-data

Wall-Brew-Co/common-beer-format:
  - source: sources/templates/LICENSE
    dest: LICENSE
    template:
      year:
        created: 2020
        current: 2024
  - source: sources/templates/CONTRIBUTING.md
    dest: CONTRIBUTING.md
    template:
      repo:
        name: common-beer-format

Wall-Brew-Co/keg:
  - source: sources/templates/LICENSE
    dest: LICENSE
    template:
      year:
        created: 2020
        current: 2024
  - source: sources/templates/CONTRIBUTING.md
    dest: CONTRIBUTING.md
    template:
      repo:
        name: keg

Wall-Brew-Co/lein-sealog:
  - source: sources/templates/LICENSE
    dest: LICENSE
    template:
      year:
        created: 2022
        current: 2024
  - source: sources/templates/CONTRIBUTING.md
    dest: CONTRIBUTING.md
    template:
      repo:
        name: lein-sealog

Wall-Brew-Co/spoon:
  - source: sources/templates/LICENSE
    dest: LICENSE
    template:
      year:
        created: 2022
        current: 2024
  - source: sources/templates/CONTRIBUTING.md
    dest: CONTRIBUTING.md
    template:
      repo:
        name: spoon
