name: Linter
on: [pull_request, workflow_dispatch]

jobs:
  spell-check:

    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true

    # This job requires the Wall Brew Bot Token, so it is only run on non-forked repositories
    if: github.repository_owner == 'Wall-Brew-Co'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.1
        with:
          ref: ${{ github.head_ref }}

      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.WALL_BREW_BOT_PAT }}
          locale: "US"
          reporter: github-pr-review
          level: error
          filter_mode: file
          ignore: "litre,millilitre,litres,millilitres"
