name: Linter
on: [pull_request, workflow_dispatch]

permissions:
  contents: read
  pull-requests: write

jobs:
  spell-check:

    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true

    # This job requires the Wall Brew Bot Token, so it is only run on non-forked repositories
    if: github.repository_owner == 'Wall-Brew-Co'
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.head_ref }}

      # https://github.com/reviewdog/action-misspell
      - name: misspell
        uses: reviewdog/action-misspell@d6429416b12b09b4e2768307d53bef58d172e962 # v1
        with:
          github_token: ${{ secrets.WALL_BREW_BOT_PAT }}
          locale: "US"
          reporter: github-pr-review
          level: error
          filter_mode: file
          ignore: "litre,millilitre,litres,millilitres"
