name: Synchronize Files

on:
  workflow_dispatch:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  sync-files:
    # This job requires the Wall Brew Bot Token, so it is only run on non-forked repositories
    if: github.repository_owner == 'Wall-Brew-Co'
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout latest commit
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # https://github.com/BetaHuhn/repo-file-sync-action
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@8b92be3375cf1d1b0cd579af488a9255572e4619 # v1.21.1
        with:
          GH_PAT: ${{ secrets.WALL_BREW_BOT_PAT }}
          GIT_EMAIL: the.wall.brew@gmail.com
          GIT_USERNAME: WallBrewBot
          PR_LABELS: synchronize, automated
          COMMIT_PREFIX: '[bot]'
          COMMIT_BODY: 'Sourced from: https://github.com/Wall-Brew-Co/rebroadcast'
