name: Synchronize Files

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  sync-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v3.6.0

      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1.21.0
        with:
          GH_PAT: ${{ secrets.WALL_BREW_BOT_PAT }}
          GIT_EMAIL: the.wall.brew@gmail.com
          GIT_USERNAME: WallBrewBot
          PR_LABELS: synchronize, automated
          COMMIT_PREFIX: '[bot]'
          COMMIT_BODY: 'Sourced from: https://github.com/Wall-Brew-Co/rebroadcast'
